//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllEmployee
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string AssessmentPeriod { get; set; }
        public string FilingDeadline { get; set; }
        public string AppraiseeMail { get; set; }
        public string AppraiseeName { get; set; }
        public string AppraiseeMail2 { get; set; }
        public string AppraiseeName2 { get; set; }
        public string Department { get; set; }
        public string JobTitle { get; set; }
        public string SeniorMail { get; set; }
        public string SeniorName { get; set; }
        public string Grade { get; set; }
        public string ManagerMail { get; set; }
        public string ManagerName { get; set; }
        public string PayrollCaclMark { get; set; }
        public string PayrollCaclComments { get; set; }
        public string PreparationOfTaxReturnMark { get; set; }
        public string PreparationOfTaxReturnComments { get; set; }
        public string ReportingToHeadOfficeMark { get; set; }
        public string ReportingToHeadOfficeComments { get; set; }
        public string EnglishSkillsMark { get; set; }
        public string EnglishSkillsComments { get; set; }
        public string ConsultingOfClientsMark { get; set; }
        public string ConsultingOfClientsComments { get; set; }
        public string SpeedOfWorkMark { get; set; }
        public string SpeedOfWorkComments { get; set; }
        public string QualityOfWorkMark { get; set; }
        public string QualityOfWorkComments { get; set; }
        public string ComplianceWithInternalProceduresMark { get; set; }
        public string ComplianceWithInternalProceduresComments { get; set; }
        public string CommunicationWithClientsMark { get; set; }
        public string CommunicationWithClientsComments { get; set; }
        public string TeamWorkMark { get; set; }
        public string TeamWorkComments { get; set; }
        public string TeachingOfSubordinatesMark { get; set; }
        public string TeachingOfSubordinatesComments { get; set; }
        public string ControlOfTeamWorkMark { get; set; }
        public string ControlOfTeamWorkComments { get; set; }
        public string OrganizationOfTeamWorkMark { get; set; }
        public string OrganizationOfTeamWorkComments { get; set; }
        public string ProactiveApproachMark { get; set; }
        public string ProactiveApproachComments { get; set; }
        public string ConsultingMark { get; set; }
        public string ConsultingComments { get; set; }
        public string DifficultyOfClientsMark { get; set; }
        public string DifficultyOfClientsComments { get; set; }
        public string EnglishLanguageMark { get; set; }
        public string EnglishLanguageComments { get; set; }
        public string MarkByManager { get; set; }
        public string MarkByManagerComments { get; set; }
    }
}
