//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpStat
    {
        public int Id { get; set; }
        public string AssessmentPeriod { get; set; }
        public string AppraiseeMail { get; set; }
        public string AppraiseeName { get; set; }
        public string Department { get; set; }
        public string JobTitle { get; set; }
        public string SeniorMail { get; set; }
        public string SeniorName { get; set; }
        public string Grade { get; set; }
        public string ManagerMail { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> MarkByManager { get; set; }
        public string MarkByManagerComments { get; set; }
    }
}
