//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksERP
{
    using System;
    using System.Collections.Generic;
    
    public  class TicketsArchive
    {
        public int Id { get; set; }
        public string Owner { get; set; }
        public string Status { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Priority { get; set; }
        public string AssignedTo { get; set; }
        public string Comment { get; set; }
        public string MailID { get; set; }
        public string AttachId { get; set; }
    }
}
